name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install protoc Go plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Generate proto files
      run: |
        protoc --go_out=paths=source_relative:proto \
               --go-grpc_out=paths=source_relative:proto \
               --proto_path=proto proto/kvstore.proto

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test ./...
